---
- name: Information
  debug:
    msg: "Must input 'yes', abort the playbook "
  when:
    - confirmed != 'yes'

- meta: end_play
  when:
    - confirmed != 'yes'

- name: Remove folder
  file:
    path: "{{ deploy_dir }}/{{ item }}"
    state: absent
  with_items:
    - bin
    - scripts
    - etc
    - share
    - cluster.id

  when: 
    - delete_type == 'binary'

- name: Remove folder
  file:
    path: "{{ deploy_dir }}"
    state: absent
  when: 
    - delete_type == 'data'
